name             'masala_zookeeper'
maintainer       'Joe Hohertz'
maintainer_email 'jhohertz@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures masala_zookeeper'
long_description 'Installs/Configures masala_zookeeper'
version          '0.1.0'

depends          'masala_base', '~> 0.1.0'
depends          'masala_ldap', '~> 0.1.0'
depends          'zookeeper', '~> 5.0.1'
